### PR TITLE
Compare client_id against grant's client

### PR DESCRIPTION
**Pull request by nsklikas**
A client could take a token from another client and use it as his own.

### CODE REVIEW

**Review by peppelinux — APPROVED** [review]

**Comment by rohe** [comment]
So, this was one of the things I fixed in the code as a result of the conformance testing.
Different solution from your proposal though.
Have to compare.

**Comment by peppelinux** [comment]
in django-oidc-op and the satosa frontend based in oidcop, due to their storage logic based on flush/dump/load/ method of session_manager, this problem is fixed by design. Here the test

https://github.com/peppelinux/SATOSA/commit/df6e9a880394422ef84afb4b672d6d28b0223e43#diff-f10182b97d02a823560e9df6c[…]778db6a2f6050bcc03337c3d67R765

anyway this PR is very important for who use oidcop with a pure inmemory storage or another inherited engine from inmemory interfaces, good job @nsklikas

**Comment by rohe** [comment]
There are 2 differences between @nsklikas proposal and mine.
I picked client_id from the session_info so my check happens a couple of lines earlier then @nsklikas's 
I use the error code invalid_grant which explicitly lists 'or was issued to another client.' as the cause of the error.

I've added the new tests to my branch since I think we should choose that one instead of this. My 2 cents.

**Comment by nsklikas** [comment]
Your solution sounds better. I will close this PR when you open one with your changes.

**Pull request closed without merging**
