### PR TITLE
docs: add prompt to refresh token requirements

### PR DESCRIPTION
**Pull request by melanger**
re https://github.com/UniversitaDellaCalabria/SATOSA-oidcop/issues/1

### CODE REVIEW

**Comment by peppelinux** [comment]
Good contribution, thank you!
@rohe we know that's something that belong to oidc certification requirements. @melanger may we have to say this in the docs?

I mean, that's not am oidcop requirement but a oidc specification one

**Comment by rohe** [comment]
True, it's an OIDC specification requirement. Though there are caveats, as always. :-/

**Comment by peppelinux** [comment]
Ok I think it's worth of it to specify this behaviour also in the documentation, specially for legacy clients and consumers that would think that oidcop has some strange behaviour :)

I would like just to underline that's something required from oidc certification, and not a free initiative of the oidcop developers :)

**Comment by melanger** [comment]
> Ok I think it's worth of it to specify this behaviour also in the documentation, specially for legacy clients and consumers that would think that oidcop has some strange behaviour :)
> 
> I would like just to underline that's something required from oidc certification, and not a free initiative of the oidcop developers :)

Note added.

**Review by peppelinux — APPROVED** [review]

**Comment by peppelinux** [comment]
@rohe this is an easy shot, once merged the official docs will be updated automatically (because it's on master branch)

**Review by rohe — APPROVED** [review]

**Pull request merged**
