### PR TITLE
Including oidcendpoint in oidc-op

### PR DESCRIPTION
**Pull request by rohe**
We're getting rid of the oidcendpoint package having it included in oidc-op.

### CODE REVIEW

**Review by peppelinux — APPROVED** [review]
ride free Roland, ride free ...

**Comment by rohe** [comment]
Could you fix the django_op/README.md conflict ?

**Comment by rohe** [comment]
Why did you close it ?? Should it not have been merged ?

**Comment by peppelinux** [comment]
done here:
https://github.com/IdentityPython/oidc-op/pull/26

**Comment by rohe** [comment]
No, #26 was into develop not into master.

**Pull request closed without merging**
