### PR TITLE
Erasing tokens

### PR DESCRIPTION
**Pull request by rohe**
If configured so the software will store information about a token outside the running code before removing it from the Grant is was created within.

### CODE REVIEW

**Comment by peppelinux** [comment]
Ok, before doing a review we need to have a new release of oidcmsg and oidcrp if you agree

I made my part here:
https://github.com/IdentityPython/JWTConnect-Python-OidcMsg/pull/56

**Comment by rohe** [comment]
Yes, we do need a new release of oidcmsg.

**Review by peppelinux — APPROVED** [review]

**Comment by peppelinux** [comment]
I'd consider to have first the oidcmsg release and then oidcrp and oidcop

PRs approved, if help is needed just tell me

**Comment by rohe** [comment]
For sure, oidcmsg first, then oidcop&oidcrp.

**Pull request merged**
