### PR TITLE
django_op example updated with develop branch

### PR DESCRIPTION
**Pull request by peppelinux**
django op example updated to oidc-op develop branch

### CODE REVIEW

**Review by rohe — APPROVED** [review]
If you're OK with this I trust you.

**Comment by peppelinux** [comment]
We could decide to do this way:

Once we have v2.0.0 I'll remove django_op example code and put there only a README that points to django-oidc-op github repository. django-oidc-op could be migrated to idpy for a better reference, as well.

django-oidc-op releases Will match the major release value of oidc-op, so once we'll have the stable release of oidc-op then I'll publish django-oidc-op v2.x.y

@c00kiemon5ter does this sound good to you?

@rohe hope to meet your taste too. The only awarness I have is that, actually, django-oidc-op is the only implementation of a persistent storage based on dump()/load()/flush() methods of oidc-op session_manager, and still have this issue:
https://github.com/IdentityPython/oidc-op/issues/36

it doesn't mean that we have a real bug in oidc-op but just that we still need to exemplify a good (official) method to implement this feature in a clear, documentable, way

I can go further with a general refactor of django-oidc-op (based on ClassView) then try to visualize more closer that problem

**Comment by rohe** [comment]
I'm fine with what you propose.
Hard to nail down #36 since I can't replicate it in my setup.

**Comment by peppelinux** [comment]
with https://github.com/IdentityPython/oidc-op/pull/59 is now all ok to me,
once we get merged https://github.com/IdentityPython/oidc-op/pull/59 in develop branch I'll move django_op example as a reference to my repository (with a view to migrating it to idpy for a more robust reference).

So I close this for now, let's merge dpop2 and sman_flush and then I'll do this chore (otherwise I get a quite mess with too much branches!)

**Pull request closed without merging**
